name: test-shuff

on:
 # schedule:
 #   - cron: "30 1 * * *"
  workflow_dispatch:
    branches:

jobs:
  build:
    env:
      PY_COLORS: "1"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 6
      matrix:
        browser: [chrome]
    steps:
    - uses: actions/checkout@v4    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        architecture: "x64"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade wheel
        #pip install -r requirements.txt
        pip install seleniumbase

    - name: Check the console scripts interface
      run: |
        seleniumbase
#        sbase

    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
        
    - name: Make sure pytest is working
      run: |
        echo "def test_1(): pass" > nothing.py
        pytest nothing.py
        
    # - name: Run pytest test_mfa_login.py --browser=chrome --xvfb
    #   run: |
    #     pytest test_mfa_login.py --browser=chrome --headless -v -s --junit-xml=junit/test-results-shuff.xml

    - name: Run pytest test_shufersal.py --browser=chrome --headless -v -s
      run: |
        pytest test_shufersal.py --browser=chrome --headless -v -s --junit-xml=junit/test-results.xml
      env:
        SHUFF_ID: ${{ secrets.SHUFF_ID }}         
