name: test-shaka

on:
 # schedule:
 #   - cron: "30 1 * * *"
  push:
    branches: [ master ]
  workflow_dispatch:
    branches:

jobs:
  build:
    env:
      PY_COLORS: "1"
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   max-parallel: 6
    #   matrix:
    #     browser: [chrome]
    steps:
    - uses: actions/checkout@v4    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        architecture: "x64"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade wheel
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
                
    - name: Check the console scripts interface
      run: |
        seleniumbase

    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
        
    - name: Make sure pytest is working
      run: |
        echo "def test_1(): pass" > nothing.py
        pytest nothing.py
        
    - name: Display Chrome binary that's used
      run: |
        python -c "from seleniumbase import undetected; print(undetected.find_chrome_executable())"

    # - name: Run pytest test_mfa_login.py --browser=chrome  --headless -v -s # --xvfb
    #   run: |
    #     pytest test_mfa_login.py --browser=chrome --headless -v -s

    - name: Run pytest test_uc_mode.py headless
      run: |
        pytest test-shaka.py -v -s
