name: test-shuff

on:
 # schedule:
 #   - cron: "30 1 * * *"
  push:
    branches: [ master ]
  workflow_dispatch:
    branches:

jobs:
  build:
    env:
      PY_COLORS: "1"
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   max-parallel: 6
    #   matrix:
    #     browser: [chrome]
    steps:
    - uses: actions/checkout@v4    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        architecture: "x64"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade wheel
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
                
    - name: Check the console scripts interface
      run: |
        seleniumbase

    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
        
    - name: Make sure pytest is working
      run: |
        echo "def test_1(): pass" > nothing.py
        pytest nothing.py
        
    - name: Display Chrome binary that's used
      run: |
        python -c "from seleniumbase import undetected; print(undetected.find_chrome_executable())"

    # - name: Run pytest test_mfa_login.py --browser=chrome  --headless -v -s # --xvfb
    #   run: |
    #     pytest test_mfa_login.py --browser=chrome --headless -v -s

    # Commented out: External site tests may fail in GitHub Actions environment
    # - name: Run pytest test_uc_mode.py headless
    #   run: |
    #     pytest test_uc_mode1.py --uc --uc-cdp --headless -v -s --proxy=${{ secrets.PROXY1 }}

    # - name: Run pytest test_uc_mode.py # --xvfb
    #   run: |
    #     pytest test_uc_mode1.py --uc --uc-cdp --headed -v -s --reruns=2 --proxy=${{ secrets.PROXY1 }}

    - name: Run pytest test_shufersal.py headless
      run: |
        # Create directories for file operations
        mkdir -p data
        # Run with new environment variables and enhanced settings
        # Note: Proxy is optional for Shufersal since stealth mode handles detection
        if [ -n "${{ secrets.PROXY1 }}" ]; then
          SAVE=True ACTIVATE=False MAX_ROWS=5 pytest test_shufersal.py --uc --uc-cdp --headless -v -s --proxy=${{ secrets.PROXY1 }}
        else
          SAVE=True ACTIVATE=False MAX_ROWS=5 pytest test_shufersal.py --uc --uc-cdp --headless -v -s
        fi
      env:
        SHUFERSAL_EMAIL: ${{ secrets.SHUFERSAL_EMAIL }}
        SHUFERSAL_PSWD: ${{ secrets.SHUFERSAL_PSWD }}

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: shufersal-test-results
        path: |
          data/*.csv
        retention-days: 7
